{
    "description": "This instance shows a simple example for throwing and catching an exception.",
    "code": {
        "path": "./1_instance_50_throw_exception.php",
        "injection_skeleton_broken": false
    },
    "discovery": {
        "rule": "./1_instance_50_throw_exception.sc",
        "method": "joern",
        "rule_accuracy": "Perfect",
        "notes": "The rule searches for a call for `THROW` on opcode level."
    },
    "compile": {
        "binary": "./1_instance_50_throw_exception.bash",
        "instruction": null,
        "dependencies": null
    },
    "expectation": {
        "type": "xss",
        "sink_file": "./1_instance_50_throw_exception.php",
        "sink_line": 15,
        "source_file": "./1_instance_50_throw_exception.php",
        "source_line": 9,
        "expectation": true
    },
    "properties": {
        "category": "D2",
        "feature_vs_internal_api": "FEATURE",
        "input_sanitizer": false,
        "source_and_sink": false,
        "negative_test_case": false
    },
    "remediation": {
        "notes": "",
        "transformation": null,
        "modeling_rule": null
    }
}